version: '3'
services:
  influxdb:
    container_name: metrics-poc-influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: app
  grafana:
    container_name: metrics-poc-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana